### ISSUE TITLE
Quick Username fix

### ISSUE THREAD

**Issue by ROMaster2** [BannerBomb/BetterDiscordThemes#4]
Thank you for maintaining this as long as you did. I'm willing to help if you need some. I can't seem to find your account on Discord; probably the unicode's fault.

Here's a quick fix for the usernames appearing as white:
```css
.da-container > h2 > .da-username
{
    color: #6F6F6F;
}
```
It's easier on the eyes than pure black is.
